dist: trusty
language: java
jdk: oraclejdk8
script:
- echo "Skipping Tests"
- echo "Running Prod Level Scripts"
- echo "" >> src/main/resources/application-prod.properties
- echo $M_TOKEN >> src/main/resources/application-prod.properties
- echo $M_DB >> src/main/resources/application-prod.properties
- echo $AU_JTOK_SEC >> src/main/resources/application-prod.properties
- echo $AU_JTOK_EX >> src/main/resources/application-prod.properties
- echo "Building package to deploy to AWS"
- ./mvnw clean package -DskipTests=true -Pprod
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  app: $AWS_APP_NAME
  env: $AWS_ENV_NAME
  zip_file: 'target/collab-service-0.0.1-SNAPSHOT.war'
  bucket_name: $AWS_BUCKET_NAME
  region: eu-central-1
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY
  on:
    branch: release
notifications:
  slack:
    secure: oLPYpfIQAJ6VteHqRbpnkIOcdR1zyY9dLDVXCYiGZ6oaMq68vW86PdHnL/goFUpNTE2hE1Y1U5eVM7c6o0VrqJb/rBxTb4gCElTwfxfTKL9l5RuHspN9kSOENjg6gR1apuMarWpZTHxrF/OUvqVOqz2m4l8rzY77wXDC0ibvnJS2gCwA4GBTRJltV2P8w9ci3WeSckaq3BBdb0ochQcyut/yZ6yxxnd4/ARHzaBTdFmlOXRhzBF1KRYni5lcrqjXiMYLi822g496UQoYXrXQY1xXolSrDnDZHfiuBrkG2k0LuvtC2XFuaRBtUBQI+km4JpKA+y+aSkX4Z+vug5WRMsdPJ4wjS9Q7w5w/rzsZWZ4k/ZTvIZJis3CiDzWOOl/an3nLpXjbyQhCrf5c25WnjOfynTp3wlZV5c1guxJy4ptm2FoE3hn1ZUHPrKruQ/X3tQorFxiLTT1L8SCycP+0Se2AcieAcDYYt71xjmVk0CnyXKuZk7nZvuYTZyxXPkF1+xdC+pFjoAiPHYQEyw+CpWql1uCn8JHWZxTuu2NDiDYxoi/oMYY/SvdwZpJ5EXVa1VStxc2QvLDhQGE3WKGTA/oAq4noydV0oONNU9NJRL/odq5+bQIXaz/jAvR32m8hIRvQE5UFmdsvq0x2t8M+IqrueUg7zyjVmiXmjAgwdoI=
